# Site settings
title: "Barry Revzin"
email: barry.revzin@gmail.com
description: "Barry's C++ Blog"
baseurl: ""
url: https://brevzin.github.io
title_image: "https://avatars1.githubusercontent.com/u/13238276?s=460&v=4"
google_analytics: "UA-127711000-1"
github_repository: https://github.com/BRevzin
post_limit: 5

# Social usernames/URLs
twitter_username: BarryRevzin
github_username:  BRevzin
linkedin_link: https://www.linkedin.com/in/barry-revzin-3a582917/
stackoverflow_link: https://stackoverflow.com/users/2069064/barry
xing_link:
facebook_link:

# Footer
footer_left: "&copy; 2017-2020 <a href=\"https://twitter.com/BarryRevzin\">Barry Revzin</a>"
footer_right: "<a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noir</a> theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  highlighter: none
  syntax_highlighter_opts:
    disable: true

permalink: pretty
exclude: [vendor]
